package: upkeep
version: '1.3.0'
author: KLXM Crossmedia
supportpage: https://github.com/klxm/upkeep
load: late
title: 'translate:upkeep_title'
perm: upkeep[]

page:
    title: 'translate:upkeep_title'
    perm: upkeep[]
    prio: 200
    block: system
    icon: 'rex-icon fa fa-wrench'
    subpages:
        frontend:
            title: 'translate:upkeep_frontend_title'
            icon: rex-icon fa fa-globe
            perm: upkeep[frontend]
        backend:
            title: 'translate:upkeep_backend_title'
            icon: rex-icon fa fa-users
            perm: admin[]
        domains:
            title: 'translate:upkeep_domains_title'
            icon: rex-icon fa fa-sitemap
            perm: upkeep[domains]
        domain_mapping:
            title: 'translate:upkeep_domain_mapping_title'
            icon: rex-icon fa fa-share
            perm: upkeep[domains]
            
requires:
    redaxo: ^5.18.1
    php: '>=8.2'

permissions:
    upkeep[]: 'translate:upkeep[]'
    upkeep[frontend]: 'translate:upkeep[frontend]'
    upkeep[domains]: 'translate:upkeep[domains]'

console_commands:
    upkeep:mode: rex_upkeep_mode_command

default_config:
    frontend_active: 0
    backend_active: 0
    frontend_password: ''
    allowed_ips: ''
    bypass_logged_in: 1
    maintenance_page_title: 'Site Maintenance'
    maintenance_page_message: 'We are currently performing maintenance. Please check back soon.'
    http_status_code: 503
    retry_after: 3600
    all_domains_locked: true
