package: upkeep
version: '1.8.1'
author: KLXM Crossmedia
supportpage: https://github.com/klxm/upkeep
load: late
title: 'translate:upkeep_title'
perm: upkeep[]

page:
    title: 'translate:upkeep_title'
    perm: upkeep[]
    prio: 200
    block: system
    icon: 'rex-icon fa fa-wrench'
    subpages:
        dashboard:
            title: 'Upkeep Dashboard'
            icon: rex-icon fa fa-dashboard
            perm: upkeep[]
        ips:
            title: 'translate:upkeep_ips_title'
            icon: rex-icon fa fa-shield
            perm: upkeep[security]
            subpages:
                threats: {title: 'translate:upkeep_ips_threats', icon: rex-icon fa fa-exclamation-triangle}
                blocked: {title: 'translate:upkeep_ips_blocked', icon: rex-icon fa fa-ban}
                positivliste: {title: 'translate:upkeep_ips_positivliste', icon: rex-icon fa fa-check-circle}
                patterns: {title: 'translate:upkeep_ips_patterns', icon: rex-icon fa fa-code}
                default_patterns: {title: 'translate:upkeep_ips_default_patterns', icon: rex-icon fa fa-cogs}
                settings: {title: 'translate:upkeep_ips_settings', icon: rex-icon fa fa-cog}
                cleanup: {title: 'translate:upkeep_ips_cleanup', icon: rex-icon fa fa-trash}
        security_advisor:
            title: 'translate:upkeep_security_advisor_title'
            icon: rex-icon fa fa-shield
            perm: upkeep[security]
            subpages:
                reports: {title: 'translate:upkeep_security_reports', icon: rex-icon fa fa-list}
                help: {title: 'translate:upkeep_security_advisor_help_title', subPath: SECURITY_ADVISOR.md, itemClass: 'pull-right', icon: rex-icon fa fa-question-circle}
        mail_security:
            title: 'Mail Security'
            icon: rex-icon fa fa-envelope-o
            perm: upkeep[security]
            subpages:
                dashboard: {title: 'Dashboard', icon: rex-icon fa fa-dashboard}
                threats: {title: 'Threat Log', icon: rex-icon fa fa-exclamation-triangle}
                badwords: {title: 'Badwords', icon: rex-icon fa fa-filter}
                blacklist: {title: 'Blacklist', icon: rex-icon fa fa-ban}
                settings: {title: 'Settings', icon: rex-icon fa fa-cog}
                cleanup: {title: 'Cleanup', icon: rex-icon fa fa-trash}
                help: {title: 'translate:upkeep_mail_security_help_title', subPath: MAIL_SECURITY.md, itemClass: 'pull-right', icon: rex-icon fa fa-question-circle}
        reporting:
            title: 'translate:upkeep_reporting_title'
            icon: rex-icon fa fa-bar-chart
            perm: upkeep[security]
            subpages:
                overview: {title: 'translate:upkeep_reporting_overview', icon: rex-icon fa fa-dashboard}
                system_health: {title: 'translate:upkeep_system_health_title', icon: rex-icon fa fa-heartbeat}
                mail_reporting: {title: 'translate:upkeep_mail_reporting_title', icon: rex-icon fa fa-paper-plane}
        maintenance:
            title: 'translate:upkeep_maintenance_title'
            icon: rex-icon fa fa-wrench
            perm: upkeep[]
            subpages:
                frontend: {title: 'translate:upkeep_frontend_title', icon: rex-icon fa fa-globe, perm: upkeep[frontend]}
                backend: {title: 'translate:upkeep_backend_title', icon: rex-icon fa fa-users, perm: admin[]}
                domains: {title: 'translate:upkeep_domains_title', icon: rex-icon fa fa-sitemap, perm: upkeep[domains]}
                help: {title: 'translate:upkeep_maintenance_help_title', subPath: MAINTENANCE.md, itemClass: 'pull-right', icon: rex-icon fa fa-question-circle}
        domain_mapping:
            title: 'translate:upkeep_domain_mapping_title'
            icon: rex-icon fa fa-share
            perm: upkeep[domain_mapping]
        help:
            title: 'translate:help'
            subPath: README.md
            itemClass: 'pull-right'
            icon: rex-icon fa fa-question-circle
            
requires:
    redaxo: ^5.18.1
    php: '>=8.2'

suggests:
    cronjob: '^2.8'  # Für automatische IPS-Datenbereinigung

permissions:
    upkeep[]: 'translate:upkeep[]'
    upkeep[frontend]: 'translate:upkeep[frontend]'
    upkeep[domains]: 'translate:upkeep[domains]'
    upkeep[domain_mapping]: 'translate:upkeep[domain_mapping]'
    upkeep[security]: 'translate:upkeep[security]'

console_commands:
    upkeep:mode: rex_upkeep_mode_command
    upkeep:ips:cleanup: rex_upkeep_ips_cleanup_command
    upkeep:security:scan: rex_upkeep_security_scan_command
    upkeep:mail-reporting:send-bundle: rex_upkeep_mail_reporting_bundle_command

default_config:
    frontend_active: 0
    backend_active: 0
    frontend_password: ''
    allowed_ips: ''
    bypass_logged_in: 1
    # IPS Configuration
    ips_active: 0
    ips_burst_limit: 10
    ips_disable_system_logging: 0
    ips_block_title: 'Access Denied'
    ips_block_message: 'Your request has been blocked by our security system.'
    ips_contact_info: ''
    ips_whitelist: []
    maintenance_page_title: 'Site Maintenance'
    maintenance_page_message: 'We are currently performing maintenance. Please check back soon.'
    http_status_code: 503
    retry_after: 3600
    all_domains_locked: false
